controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
lista:
    path: /lista
    controller: App\Controller\PostController::index
homepage:
    path: /
    controller: App\Controller\SecurityController::login
